agv:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    publish_rate: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 1.0

    wheel_separation: 0.376
    wheel_radius: 0.03225
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.9  # m/s
        min_velocity           : -0.9 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.80  # m/s^2
        #min_acceleration       : -0.80 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14 # rad/s
        #min_velocity           : -3.14 # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.570  # rad/s^2
        #min_acceleration       : -1.570  # rad/s^2


